### ISSUE TITLE
Add ability to provide lists of data

### ISSUE THREAD

**Issue by azohra** [azohra/elir#2]
We currently have: 
  ```  - TESTS:  spec/a_spec.rb, spec/b_spec.rb```

it would be great to have
 ```  
 - TESTS: 
    - spec/a_spec.rb
    - spec/b_spec.rb```

**Comment by florinpatrascu** [comment]
This elir config fragment (from elir.yml):

```yml
  # create a cartesian product with the elements below
  env:
    - languages: fr, en
    - devices: mobile, desktop
    - servers: local
```
will become:

```yml
  # create a cartesian product with the elements below
  env:
    languages:
      - fr
      - en
    devices:
      - mobile
      - desktop
    servers:
      - local
```

please observe how: `languages`, `devices`, and so on, are becoming keys in the `env` map!

**Comment by florinpatrascu** [comment]
the `context_env` will suffer the same transformation. The correct form will be:

```yml
  # pour the next values into the environment, as is
  context_env:
    alpha: beta
    gamma: delta
```

and not:

```yml
  # pour the next values into the environment, as is
  context_env:
    - alpha: beta
    - gamma: delta
``` 
as it is in the current version
